dependencies:
- name: postgresql
  version: 3.16.1 #appVersion: 10.7.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: postgresql.enabled
- name: redis
  version: 6.4.4 #appVersion: 4.0.14
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
- name: elasticsearch
  version: 1.24.0 #appVersion: 6.7.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch.enabled
