commonLabels: {}
commonAnnotations: {}
commonConfig:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      memory: 512Mi
      cpu: 300m
  maxHeartbeatFailures: 10
  requestTimeout: 10
  cache:
    enabled: true
    type: redis
    ttl: 60
    host: "localhost"
    port: 6379
    password: ""
    # # sharedInfraToken can be manually set here or a random 64 character code will be generated
    # sharedInfraToken:
    # # secretsToken can be manually set here or a random 32 character code will be generated
    # secretsToken:
  log:
    level: info
    # log critical if spawn take more than this value (in seconds)
    thresholdCritical: "480"
    # log warning if spawn take more than this value (in seconds)
    thresholdWarning: "360"
    # Max service logs size in bytes (default: 15MB)
    serviceMaxSize: "15728640"
    # Max step logs size in bytes (default: 15MB)
    stepMaxSize: "15728640"
  graylog:
    enabled: false
    accessToken: ""
    stream: ""
    url: ""
    # Example: X-OVH-TOKEN. You can use many keys: aaa,bbb
    extraKey: ""
    # value for extraKey field. For many keys: valueaaa,valuebbb
    extraValue: ""
    # Example: thot.ovh.com
    host: ""
    # Example: 12202
    port: 0
    # tcp or udp
    protocol: ""
  persistence:
    enabled: true
    size: 8Gi
    # storageClass: ""
    accessModes:
      - "ReadWriteOnce"
  serviceType: ClusterIP
  servicePort: 80
  sharedInfraToken:
  secretsToken:
  urls:
    insecure: false
    # Please set these values if ingress is enabled
    api:
      public:
    ui:
      public:
    hooks:
      public:

image:
  imagePullSecrets: {}
  ui:
    registry: "docker.io"
    repository: ovhcom/cds-ui
    tag: 0.38.1
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
  engine:
    registry: "docker.io"
    repository: ovhcom/cds-engine
    tag: 0.38.1
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent

rbac:
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: cds.local
      paths:
        - path: /
          backend:
            name: ui
            port: http

  tls: []
  #  - secretName: cds-tls
  #    hosts:
  #      - cds.local

api:
  replicas: 1
  ports:
    grpc: 8082
    http: 8081
  service:
    http: {}
      # type:
      # port:
    grpc: {}
      # type:
      # port:
  # Uncomment these to override the commonConfig
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}
  # resources:
  #   requests:
  #     memory: 512Mi
  #     cpu: 300m
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  persistence:
    enabled: true
    mountPath: "/app/artifacts"
    accessModes:
      - "ReadWriteOnce"
    # hostPath: ""
    size: 8Gi
  updateStrategy:
    type: RollingUpdate
  config:
    # if no model and no os/arch is specified in your job's requirements then spawn worker on this architecture (example: amd64, arm, 386)
    defaultArch: "amd64"
    # if no model and os/arch is specified in your job's requirements then spawn worker on this operating system (example: freebsd, linux, windows)
    defaultOS: "linux"
    # Either filesystem local storage or Openstack Swift Storage are supported
    smtp:
      enabled: false
      from: "no-reply@cds.local"
      host: ""
      password: ""
      port: 25
      tls: false
      user: ""
    artifact:
      mode: local
      local:
        baseDirectory: "/app/artifacts"
      openstack:
        # Use if your want to prefix containers for CDS Artifacts
        containerPrefix: ""
        # True if you want to disable Temporary URL in file upload
        disableTempURL: false
        # Openstack Domain, generally value of $OS_DOMAIN_NAME, v3 auth only
        domain: ""
        # Openstack Password, generally value of $OS_PASSWORD
        password: ""
        # Region, generally value of $OS_REGION_NAME
        region: ""
        # Openstack Tenant, generally value of $OS_TENANT_NAME, v2 auth only
        tenant: ""
        # Authentication Endpoint, generally value of $OS_AUTH_URL
        url: ""
        # Openstack Username, generally value of $OS_USERNAME
        username: ""
    auth:
      type: local
      defaultGroup: ""
      local:
        signupAllowedDomains: ""
      ldap:
        base: "dc=myorganization,dc=com"
        # Define it if ldapsearch need to be authenticated
        bindDN: ""
        # Define it if ldapsearch need to be authenticated
        bindPwd: ""
        dn: "uid=%s,ou=people,dc=myorganization,dc=com"
        enable: false
        fullname: "{{.givenName}} {{.sn}}"
        host: ""
        port: 636
        ssl: true
    database:
      # Maximum wait for connection, in seconds
      connectTimeout: 10
      host: "localhost"
      # DB Max connection
      maxconn: 20
      name: "cds"
      password: "cds"
      port: 5432
      # Set a specific role to run SET ROLE for each connection
      # role = ""
      # DB SSL Mode: require (default), verify-full, or disable
      sslmode: "disable"
      # Statement timeout value in milliseconds
      timeout: 3000
      user: "cds"
    directories:
      download: "/app"
      keys: "/app/keys"
    events:
      kafka:
        enabled: false
        broker: ""
        maxmessagebytes: 10000000
        password: ""
        topic: ""
        user: ""
    features:
      izanami:
        enabled: false
        apiurl: ""
        clientid: ""
        clientsecret: ""
        # Token shared between Izanami and CDS to be able to send webhooks from izanami
        token: ""
    log: {}
      # Override the commonConfig.log settings here
      # Max service logs size in bytes (default: 15MB)
      #serviceMaxSize: 0
      # Max step logs size in bytes (default: 15MB)
      #stepMaxSize: 0
    providers: []
      # - name: sample-provider
        # token: whrzzxy2qxe5l3b5qzuuio4m5kyo126z
    services: []
      # - healthPath: "/cds"
        # healthPort: "443"
        # healthUrl: "https://ovh.github.io"
        # name: "sample-service"
        # path: "/cds"
        # port: "443"
        # type: "doc"
        # url: "https://ovh.github.io"
    counts:
      api: 1
      dbmigrate: 0
      elasticsearch: 0
      hatchery: 1
      hooks: 1
      repositories: 1
      vcs: 1
    vault:
      enable: false
      key:
ui:
  enabled: true
  replicas: 1
  port: 2015
  service: {}
  #   type:
  #   port:
  # Uncomment these to override the commonConfig
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}
  # resources:
  #   requests:
  #     memory: 512Mi
  #     cpu: 300m
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  config:
    baseUrl: /
repositories:
  enabled: true
  replicas: 1
  port: 8085
  service: {}
  #   type:
  #   port:
  # # Uncomment these to override the commonConfig
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}
  # resources:
  #   requests:
  #     memory: 512Mi
  #     cpu: 300m
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  persistence:
    enabled: true
    mountPath: "/app/repositories"
    accessModes:
      - "ReadWriteOnce"
    # hostPath: ""
    size: 8Gi
  updateStrategy:
    type: RollingUpdate
  enabled: true
  config:
    retention:
      operation: 5
      repositories: 10
hooks:
  enabled: true
  replicas: 1
  port: 8083
  service: {}
  #   type:
  #   port:
  # # Uncomment these to override the commonConfig
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}
  # resources:
  #   requests:
  #     memory: 512Mi
  #     cpu: 300m
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  enabled: true
  config:
    executionHistory: 10
    retryDelay: 120
    retryError: 3
    urlPublic: ""
vcs:
  enabled: true
  replicas: 1
  port: 8084
  service: {}
  #   type:
  #   port:
  # # Uncomment these to override the commonConfig
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}
  # resources:
  #   requests:
  #     memory: 512Mi
  #     cpu: 300m
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  enabled: true
  config:
    bitbucket:
      enabled: false
      url: "https://bitbucket.org"
      consumerKey: ""
      disablePolling: false
      disableWebHooks: false
      privateKey: ""
      proxyWebhook: ""
      token: ""
      username: ""
      status:
        disable: false
    github:
      enabled: false
      url: "https://github.com"
      clientId: ""
      clientSecret: ""
      disablePolling: false
      disableWebHooks: false
      proxyWebhook: ""
      token: ""
      username: ""
      status:
        disable: false
        showDetail: false
    gitlab:
      enabled: false
      url: "https://gitlab.com"
      appId: ""
      disablePolling: false
      disableWebHooks: false
      proxyWebhook: ""
      secret: ""
      status:
        disable: false
        showDetail: false
hatchery:
  enabled: true
  replicas: 1
  port: 8086
  service: {}
  #   type:
  #   port:
  # # Uncomment these to override the commonConfig
  # nodeSelector: {}
  # tolerations: []
  # affinity: {}
  # resources:
  #   requests:
  #     memory: 512Mi
  #     cpu: 300m
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  enabled: true
  config:
    defaultMemory: 256
    nbProvision: 1
    workerTTL: 10
    provision:
      disabled: false
      frequency: 30
      graceTimeQueued: 4
      maxConcurrentProvisioning: 10
      maxWorker: 20
      registerFrequency: 60

redis:
  enabled: true
  ## Add any overrides for the stable/redis chart here

postgresql:
  enabled: true
  ## Add any overrides for the stable/postgresql chart here

elasticsearch:
  enabled: true
  ## Add any overrides for the stable/elasticsearch chart here
  data:
    replicas: 1
  client:
    replicas: 1
  master:
    replicas: 1
  cluster:
    env:
      MINIMUM_MASTER_NODES: 1
      EXPECTED_MASTER_NODES: 1
      RECOVER_AFTER_MASTER_NODES: 1
