{{- if and (default .Values.commonConfig.persistence.enabled .Values.api.persistence.enabled) (not .Values.api.persistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cds.fullname" . }}-api-pvc
  labels:
    app.kubernetes.io/name: {{ include "cds.name" . }}-api
    helm.sh/chart: {{ include "cds.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cds.name" . }}-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  accessModes:
  - {{ .Values.api.persistence.accessMode | default .Values.commonConfig.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size | default .Values.commonConfig.persistence.size | quote }}
  {{- if and (.Values.api.persistence.storageClass | default .Values.commonConfig.persistence.storageClass) (not .Values.api.persistence.hostPath) -}}
  {{- if (eq "-" (.Values.api.persistence.storageClass | default .Values.commonConfig.persistence.storageClass)) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.api.persistence.storageClass | default .Values.commonConfig.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
