apiVersion: v1
{{- $service := "api" }}
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}"
    app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service }}
    app.kubernetes.io/role: "{{ $service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  type: {{ .Values.api.service.type | default .Values.commonConfig.serviceType }}
  ports:
    - port: {{ .Values.api.service.http.port | default .Values.commonConfig.servicePort | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
    - name: grpc
      port: {{ .Values.api.service.grpc.port | default 8082 }}
      targetPort: grpc
  selector:
    app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service }}
    app.kubernetes.io/role: "{{ $service }}"
