{{- if .Values.elasticsearch.enabled -}}
{{- $service := "elasticsearch" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}"
    app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service }}
    app.kubernetes.io/role: "{{ $service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  type: {{ .Values.commonConfig.serviceType }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service }}
    app.kubernetes.io/role: "{{ $service }}"
{{- end }}{{/*disable/enable all*/}}
