{{- if .Values.hatchery.enabled -}}
{{- $service := "hatchery:kubernetes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
  labels:
    app: {{ template "cds.name" . }}
    chart: "{{ .Chart.Name }}"
    role: "{{ $service | replace ":" "-" }}"
    instance: "{{ .Release.Name }}"
    managed-by: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.hatchery.replicas }}
  selector:
    matchLabels:
      app: {{ template "cds.name" . }}
      role: "{{ $service | replace ":" "-" }}"
  template:
    metadata:
      labels:
        app: {{ template "cds.name" . }}
        role: "{{ $service | replace ":" "-" }}"
    spec:
      serviceAccountName: {{ template "cds.serviceAccountName" . }}
      containers:
        - name: "{{ template "cds.fullname" . }}-{{ $service | replace ":" "-" }}-k8s"
          image: "{{ .Values.image.engine.registry }}/{{ .Values.image.engine.repository }}:{{ .Values.image.engine.tag }}"
          imagePullPolicy: {{ .Values.image.engine.pullPolicy | quote }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - "CDS_HATCHERY_KUBERNETES_COMMONCONFIGURATION_NAME=\"$(hostname)\" /app/cds-engine-linux-amd64 start {{ $service }} --config /config/config.toml"
          env:
            - name: CDS_HATCHERY_KUBERNETES_COMMONCONFIGURATION_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "cds.fullname" . }}-secrets
                  key: sharedInfraToken
          ports:
            - name: http
              containerPort: {{ .Values.hatchery.port }}
          {{- if or (.Values.hatchery.resources) (.Values.commonConfig.resources)}}
          resources:
          {{- .Values.hatchery.resources | default .Values.commonConfig.resources | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cds-config
              mountPath: /config
      volumes:
        - name: cds-config
          configMap:
            name: cds-configmap
      {{- if or (.Values.hatchery.nodeSelector) (.Values.commonConfig.nodeSelector)}}
      nodeSelector:
      {{- .Values.hatchery.nodeSelector | default .Values.commonConfig.nodeSelector| toYaml | nindent 8 }}
      {{- end }}
      {{- if or (.Values.hatchery.affinity) (.Values.commonConfig.affinity)}}
      affinity:
      {{- .Values.hatchery.affinity | default .Values.commonConfig.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if or (.Values.hatchery.tolerations) (.Values.commonConfig.tolerations)}}
      tolerations:
      {{- .Values.hatchery.tolerations | default .Values.commonConfig.tolerations | toYaml | nindent 8 }}
      {{- end }}
{{- end }}{{/*disable/enable all*/}}
