{{- if .Values.hatchery.enabled }}
{{- $service := "hatchery:kubernetes" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}"
    app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
    app.kubernetes.io/role: "{{ $service | replace ":" "-" }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  type: {{ .Values.hatchery.service.type | default .Values.commonConfig.serviceType }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
    app.kubernetes.io/role: "{{ $service | replace ":" "-" }}"
{{- end }}{{/*disable/enable all*/}}
