{{- if .Values.hatchery.enabled }}
{{- $service := "hatchery:kubernetes" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
  labels:
    app.kubernetes.io/name: {{ include "cds.name" . }}-{{ $service | replace ":" "-" }}
    {{- include "cds.baselabels" . | nindent 4 }}
spec:
  type: {{ .Values.hatchery.service.type | default .Values.commonConfig.serviceType }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "cds.name" . }}-{{ $service | replace ":" "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}{{/*disable/enable all*/}}
