{{- if .Values.hatchery.enabled -}}
{{- $service := "hatchery:kubernetes" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
  labels:
    helm.sh/chart: "{{ .Chart.Name }}"
    app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
    app.kubernetes.io/role: "{{ $service | replace ":" "-" }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.hatchery.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
      app.kubernetes.io/role: "{{ $service | replace ":" "-" }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
        app.kubernetes.io/role: "{{ $service | replace ":" "-" }}"
    spec:
      containers:
        - name: "{{ template "cds.fullname" . }}-{{ $service | replace ":" "-" }}-k8s"
          image: "{{ .Values.image.engine.registry }}/{{ .Values.image.engine.repository }}:{{ .Values.image.engine.tag }}"
          imagePullPolicy: {{ .Values.image.engine.pullPolicy | quote }}
          command: ["/bin/sh"]
          args:
            - "-c"
            - "echo $CDS_K8S_FILE_CONTENT | base64 --decode > {{ .Values.hatchery.config.kubeconfig }} && CDS_HATCHERY_KUBERNETES_COMMONCONFIGURATION_NAME=\"$(hostname)\" /app/cds-engine-linux-amd64 start {{ $service }} --config /config/config.toml"
          env:
            - name: CDS_HATCHERY_KUBERNETES_KUBERNETESCONFIGFILE
              value: {{ .Values.hatchery.config.kubeconfig }}
            - name: CDS_K8S_FILE_CONTENT
              valueFrom:
                secretKeyRef:
                  name: {{ template "cds.fullname" . }}-secrets
                  key: kubeconfig
            - name: CDS_HATCHERY_KUBERNETES_COMMONCONFIGURATION_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "cds.fullname" . }}-secrets
                  key: sharedInfraToken
          ports:
            - name: http
              containerPort: {{ .Values.hatchery.port }}
          {{- if or (.Values.hatchery.resources) (.Values.commonConfig.resources)}}
          resources:
          {{- .Values.hatchery.resources | default .Values.commonConfig.resources | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cds-config
              mountPath: /config
      volumes:
        - name: cds-config
          configMap:
            name: cds-configmap
      {{- if or (.Values.hatchery.nodeSelector) (.Values.commonConfig.nodeSelector)}}
      nodeSelector:
      {{- .Values.hatchery.nodeSelector | default .Values.commonConfig.nodeSelector| toYaml | nindent 8 }}
      {{- end }}
      {{- if or (.Values.hatchery.affinity) (.Values.commonConfig.affinity)}}
      affinity:
      {{- .Values.hatchery.affinity | default .Values.commonConfig.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if or (.Values.hatchery.tolerations) (.Values.commonConfig.tolerations)}}
      tolerations:
      {{- .Values.hatchery.tolerations | default .Values.commonConfig.tolerations | toYaml | nindent 8 }}
      {{- end }}
{{- end }}{{/*disable/enable all*/}}
