{{- if .Values.hatchery.enabled }}
{{- $service := "hatchery:kubernetes" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service | replace ":" "-" }}
  labels:
    app: {{ template "cds.name" . }}
    chart: "{{ .Chart.Name }}"
    role: "{{ $service | replace ":" "-" }}"
    instance: "{{ .Release.Name }}"
    managed-by: "{{ .Release.Service }}"
spec:
  type: {{ .Values.hatchery.service.type | default .Values.commonConfig.serviceType }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: {{ template "cds.name" . }}
    role: "{{ $service | replace ":" "-" }}"
{{- end }}{{/*disable/enable all*/}}
