{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "cds.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}"
    app: {{ template "cds.name" . }}
    instance: "{{ .Release.Name }}"
    managed-by: "{{ .Release.Service }}"
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces", "pods"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "cds.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}"
    app: {{ template "cds.name" . }}
    instance: "{{ .Release.Name }}"
    managed-by: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "cds.fullname" . }}
subjects:
  - name: {{ template "cds.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
    kind: ServiceAccount
{{- end -}}
