{{- if .Values.repositories.enabled }}
{{- $service := "repositories" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service }}
  labels:
    chart: "{{ .Chart.Name }}"
    name: {{ include "cds.fullname" . }}-{{ $service }}
    role: "{{ $service }}"
    instance: "{{ .Release.Name }}"
    managed-by: "{{ .Release.Service }}"
spec:
  type: {{ .Values.repositories.service.type | default .Values.commonConfig.serviceType }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: {{ template "cds.name" . }}
    role: "{{ $service }}"
{{- end }}{{/*disable/enable all*/}}
