{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cds.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "cds.name" . }}-secrets
    helm.sh/chart: {{ include "cds.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.commonConfig.sharedInfraToken }}
  sharedInfraToken: {{ .Values.commonConfig.sharedInfraToken | b64enc | quote }}
  {{- else }}
  sharedInfraToken: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- if .Values.commonConfig.secretsToken }}
  secretsToken: {{ .Values.commonConfig.secretsToken | b64enc | quote }}
  {{- else }}
  secretsToken: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.api.config.database.password }}
  postgresPassword: {{ .Values.api.config.database.password | b64enc | quote }}
  {{- else }}
  postgresPassword: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  kubeconfig: {{ .Files.Get "kubeconfig.yaml" | default "" | b64enc | b64enc }}
{{- end -}}
