apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cds.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "cds.name" . }}-secrets
    {{- template "cds.baselabels" . }}
type: Opaque
data:
  {{- if .Values.commonConfig.sharedInfraToken }}
  sharedInfraToken: {{ .Values.commonConfig.sharedInfraToken | b64enc | quote }}
  {{- else }}
  {{- if .Release.IsInstall }}
  sharedInfraToken: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
  {{- end -}}
  {{- if .Values.commonConfig.secretsToken }}
  secretsToken: {{ .Values.commonConfig.secretsToken | b64enc | quote }}
  {{- else }}
  {{- if .Release.IsInstall }}
  secretsToken: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end -}}
  {{- end }}
  {{- if not .Values.postgresql.enabled }}
  postgresPassword: {{ .Values.api.config.database.password | b64enc | quote }}
  {{- end }}
  {{- if not .Values.redis.enabled }}
  redisPassword: {{ .Values.commonConfig.cache.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.vcs.config.bitbucket.enabled }}
  bitbucketPrivateKey: {{ .Values.vcs.config.bitbucket.privateKey | join "\n" | b64enc | quote }}
  {{- if .Values.vcs.config.bitbucket.consumerKey }}
  bitbucketConsumerKey: {{ .Values.vcs.config.bitbucket.consumerKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.vcs.config.bitbucket.token }}
  bitbucketToken: {{ .Values.vcs.config.bitbucket.token | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.vcs.config.github.enabled }}
  githubClientSecret: {{ .Values.vcs.config.github.clientSecret | b64enc | quote }}
  {{- if .Values.vcs.config.github.token }}
  githubToken: {{ .Values.vcs.config.github.token | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.vcs.config.gitlab.enabled }}
  bitbucketPrivateKey: {{ .Values.vcs.config.gitlab.secret | join "\n" | b64enc | quote }}
  {{- end }}
  kubeconfig: {{ .Files.Get .Values.hatchery.config.kubeconfig.localPath | b64enc | b64enc | quote }}
