{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
{{- if .Values.image.imagePullSecrets }}
imagePullSecrets: {{ toYaml .Values.image.imagePullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: {{ template "cds.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "cds.name" . }}
    chart: "{{ .Chart.Name }}"
    instance: "{{ .Release.Name }}"
    managed-by: "{{ .Release.Service }}"
{{- end -}}
