apiVersion: v1
{{- $service := "ui" }}
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service }}
  labels:
    app.kubernetes.io/name: {{ include "cds.name" . }}-{{ $service }}
    {{- include "cds.baselabels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type | default .Values.commonConfig.serviceType }}
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
  selector:
    app.kubernetes.io/name: {{ include "cds.name" . }}-{{ $service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
