{{- if .Values.vcs.enabled }}
{{- $service := "vcs" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cds.fullname" . }}-{{ $service }}
  labels:
    app.kubernetes.io/name: {{ include "cds.name" . }}-{{ $service }}
    {{- include "cds.baselabels" . | nindent 4 }}
spec:
  type: {{ default .Values.commonConfig.serviceType .Values.vcs.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "cds.name" . }}-{{ $service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}{{/*disable/enable all*/}}
